version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: sf1-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: sf1
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - sf1-network

  redis:
    image: redis:7-alpine
    container_name: sf1-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sf1-network

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: sf1-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/sf1?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    networks:
      - sf1-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: sf1-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    networks:
      - sf1-network

volumes:
  mongodb_data:
  redis_data:

networks:
  sf1-network:
    driver: bridge